### ISSUE TITLE
群晖DOCKER部署的 但是admin/123456进不去 请问怎么解决？

### ISSUE THREAD

**Issue by keem0331** [xianyu-one/surveyking-docker#3]
群晖DOCKER部署的   但是admin/123456进不去   请问怎么解决？

**Comment by keem0331** [comment]
能直接告诉我账号密码是什么吗？或者怎么在容器配置环境变量里面怎么设置账号密码

**Comment by xianyu-one** [comment]
请确保你已阅读并理解项目自述文件，本项目仅为卷王的容器化方案，并没有对官方的数据库初始化、及官方的jar文件做任何修改，请参考自述文件完成应用部署，并使用admin/123456进行登录。
