### ISSUE TITLE
确实错误，你可以试一下，我在卷王群里大家也是同样的情况。

### ISSUE THREAD

**Issue by keem0331** [xianyu-one/surveyking-docker#4]
确实错误，你可以试一下，我在卷王群里大家也是同样的情况。

**Comment by xianyu-one** [comment]
请再次确认自己的操作是否有问题，卷王需要通过一个sql脚本来初始化数据库，请确保将`https://raw.githubusercontent.com/xianyu-one/surveyking-docker/main/sqls/init-mysql.sql`下载到本地并挂载至mysql容器的`/docker-entrypoint-initdb.d`目录，密码不对没有初始化成功一定是这个问题导致的。

文档中创建放置初始化脚本的部分漏掉了一个s，所以如果你不理解容器和它目录挂载的实际意义就会有这个问题。 自述文件的疏漏已更正，希望你能再按照自述文件的描述再进行操作一次。

另外，提问题除了描述自己遇到的情况，也请附上你的配置截图及操作步骤的流程，否则我很难帮你解决问题。

**Comment by keem0331** [comment]
感谢大佬
