### ISSUE TITLE
docker-compose 官方文档已更新

### ISSUE THREAD

**Issue by javahuang** [xianyu-one/surveyking-docker#5]
https://surveyking.cn/open-source/deploy/docker-compose-deploy

感谢 @xianyu-one ，因为最新版的 surveyking 版本已更新，所以对应的 compose 文档也重新做了调整

**Comment by xianyu-one** [comment]
感谢作者提醒，既然官方已更新并采纳本仓库的文档，那么本仓库的使命也已经完成了，仓库将归档
